/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WebhookRequestBuilder, WebhookRequestBuilderRequestsMetadata } from './webhook/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Stripe
 */
export interface StripeRequestBuilder extends BaseRequestBuilder<StripeRequestBuilder> {
    /**
     * The Webhook property
     */
    get webhook(): WebhookRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const StripeRequestBuilderUriTemplate = "{+baseurl}/Stripe";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const StripeRequestBuilderNavigationMetadata: Record<Exclude<keyof StripeRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    webhook: {
        requestsMetadata: WebhookRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
