/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFromSingaporeWebApiEndpointsUserGetUserSubscriptionsResponseFromDiscriminatorValue, type FromSingaporeWebApiEndpointsUserGetUserSubscriptionsResponse } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /User/{UserId}/Subscription
 */
export interface SubscriptionRequestBuilder extends BaseRequestBuilder<SubscriptionRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FromSingaporeWebApiEndpointsUserGetUserSubscriptionsResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<FromSingaporeWebApiEndpointsUserGetUserSubscriptionsResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SubscriptionRequestBuilderUriTemplate = "{+baseurl}/User/{UserId}/Subscription";
/**
 * Metadata for all the requests in the request builder.
 */
export const SubscriptionRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: SubscriptionRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createFromSingaporeWebApiEndpointsUserGetUserSubscriptionsResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
