/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFromSingaporeWebApiEndpointsUserCreateUserSubscriptionResponseFromDiscriminatorValue, type FromSingaporeWebApiEndpointsUserCreateUserSubscriptionResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /User/{UserId}/Subscription/{PlanId}
 */
export interface WithPlanItemRequestBuilder extends BaseRequestBuilder<WithPlanItemRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FromSingaporeWebApiEndpointsUserCreateUserSubscriptionResponse>}
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<FromSingaporeWebApiEndpointsUserCreateUserSubscriptionResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithPlanItemRequestBuilderUriTemplate = "{+baseurl}/User/{UserId}/Subscription/{PlanId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithPlanItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: WithPlanItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createFromSingaporeWebApiEndpointsUserCreateUserSubscriptionResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
