/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FromSingaporeWebApiDtosDomainDto}
 */
// @ts-ignore
export function createFromSingaporeWebApiDtosDomainDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFromSingaporeWebApiDtosDomainDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FromSingaporeWebApiDtosLinkDto}
 */
// @ts-ignore
export function createFromSingaporeWebApiDtosLinkDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFromSingaporeWebApiDtosLinkDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FromSingaporeWebApiDtosPlanDto_PlanFeaturesDto}
 */
// @ts-ignore
export function createFromSingaporeWebApiDtosPlanDto_PlanFeaturesDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFromSingaporeWebApiDtosPlanDto_PlanFeaturesDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FromSingaporeWebApiDtosPlanDto}
 */
// @ts-ignore
export function createFromSingaporeWebApiDtosPlanDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFromSingaporeWebApiDtosPlanDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FromSingaporeWebApiDtosSubscriptionDto_PlanFeaturesDto}
 */
// @ts-ignore
export function createFromSingaporeWebApiDtosSubscriptionDto_PlanFeaturesDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFromSingaporeWebApiDtosSubscriptionDto_PlanFeaturesDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FromSingaporeWebApiDtosSubscriptionDto}
 */
// @ts-ignore
export function createFromSingaporeWebApiDtosSubscriptionDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFromSingaporeWebApiDtosSubscriptionDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FromSingaporeWebApiEndpointsDomainListDomainsResponse}
 */
// @ts-ignore
export function createFromSingaporeWebApiEndpointsDomainListDomainsResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFromSingaporeWebApiEndpointsDomainListDomainsResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FromSingaporeWebApiEndpointsDomainQueryDomainsResponse}
 */
// @ts-ignore
export function createFromSingaporeWebApiEndpointsDomainQueryDomainsResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFromSingaporeWebApiEndpointsDomainQueryDomainsResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FromSingaporeWebApiEndpointsLinkCreateLinkRequest}
 */
// @ts-ignore
export function createFromSingaporeWebApiEndpointsLinkCreateLinkRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFromSingaporeWebApiEndpointsLinkCreateLinkRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FromSingaporeWebApiEndpointsLinkListLinksResponse}
 */
// @ts-ignore
export function createFromSingaporeWebApiEndpointsLinkListLinksResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFromSingaporeWebApiEndpointsLinkListLinksResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FromSingaporeWebApiEndpointsPlanListPlansResponse}
 */
// @ts-ignore
export function createFromSingaporeWebApiEndpointsPlanListPlansResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFromSingaporeWebApiEndpointsPlanListPlansResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FromSingaporeWebApiEndpointsUserGetUserSubscriptionsResponse}
 */
// @ts-ignore
export function createFromSingaporeWebApiEndpointsUserGetUserSubscriptionsResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFromSingaporeWebApiEndpointsUserGetUserSubscriptionsResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FromSingaporeWebApiExtensionsIdentityInfoResponse}
 */
// @ts-ignore
export function createFromSingaporeWebApiExtensionsIdentityInfoResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFromSingaporeWebApiExtensionsIdentityInfoResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MicrosoftAspNetCoreAuthenticationBearerTokenAccessTokenResponse}
 */
// @ts-ignore
export function createMicrosoftAspNetCoreAuthenticationBearerTokenAccessTokenResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMicrosoftAspNetCoreAuthenticationBearerTokenAccessTokenResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MicrosoftAspNetCoreHttpHttpValidationProblemDetails_errors}
 */
// @ts-ignore
export function createMicrosoftAspNetCoreHttpHttpValidationProblemDetails_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMicrosoftAspNetCoreHttpHttpValidationProblemDetails_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MicrosoftAspNetCoreHttpHttpValidationProblemDetails}
 */
// @ts-ignore
export function createMicrosoftAspNetCoreHttpHttpValidationProblemDetailsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMicrosoftAspNetCoreHttpHttpValidationProblemDetails;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MicrosoftAspNetCoreIdentityDataForgotPasswordRequest}
 */
// @ts-ignore
export function createMicrosoftAspNetCoreIdentityDataForgotPasswordRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMicrosoftAspNetCoreIdentityDataForgotPasswordRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MicrosoftAspNetCoreIdentityDataInfoRequest}
 */
// @ts-ignore
export function createMicrosoftAspNetCoreIdentityDataInfoRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMicrosoftAspNetCoreIdentityDataInfoRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MicrosoftAspNetCoreIdentityDataLoginRequest}
 */
// @ts-ignore
export function createMicrosoftAspNetCoreIdentityDataLoginRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMicrosoftAspNetCoreIdentityDataLoginRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MicrosoftAspNetCoreIdentityDataRefreshRequest}
 */
// @ts-ignore
export function createMicrosoftAspNetCoreIdentityDataRefreshRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMicrosoftAspNetCoreIdentityDataRefreshRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MicrosoftAspNetCoreIdentityDataRegisterRequest}
 */
// @ts-ignore
export function createMicrosoftAspNetCoreIdentityDataRegisterRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMicrosoftAspNetCoreIdentityDataRegisterRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MicrosoftAspNetCoreIdentityDataResendConfirmationEmailRequest}
 */
// @ts-ignore
export function createMicrosoftAspNetCoreIdentityDataResendConfirmationEmailRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMicrosoftAspNetCoreIdentityDataResendConfirmationEmailRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MicrosoftAspNetCoreIdentityDataResetPasswordRequest}
 */
// @ts-ignore
export function createMicrosoftAspNetCoreIdentityDataResetPasswordRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMicrosoftAspNetCoreIdentityDataResetPasswordRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MicrosoftAspNetCoreIdentityDataTwoFactorRequest}
 */
// @ts-ignore
export function createMicrosoftAspNetCoreIdentityDataTwoFactorRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMicrosoftAspNetCoreIdentityDataTwoFactorRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MicrosoftAspNetCoreIdentityDataTwoFactorResponse}
 */
// @ts-ignore
export function createMicrosoftAspNetCoreIdentityDataTwoFactorResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMicrosoftAspNetCoreIdentityDataTwoFactorResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MicrosoftAspNetCoreMvcProblemDetails}
 */
// @ts-ignore
export function createMicrosoftAspNetCoreMvcProblemDetailsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMicrosoftAspNetCoreMvcProblemDetails;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFromSingaporeWebApiDtosDomainDto(fromSingaporeWebApiDtosDomainDto: Partial<FromSingaporeWebApiDtosDomainDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "description": n => { fromSingaporeWebApiDtosDomainDto.description = n.getStringValue(); },
        "id": n => { fromSingaporeWebApiDtosDomainDto.id = n.getStringValue(); },
        "name": n => { fromSingaporeWebApiDtosDomainDto.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFromSingaporeWebApiDtosLinkDto(fromSingaporeWebApiDtosLinkDto: Partial<FromSingaporeWebApiDtosLinkDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "description": n => { fromSingaporeWebApiDtosLinkDto.description = n.getStringValue(); },
        "domainId": n => { fromSingaporeWebApiDtosLinkDto.domainId = n.getStringValue(); },
        "id": n => { fromSingaporeWebApiDtosLinkDto.id = n.getStringValue(); },
        "linkExpirationId": n => { fromSingaporeWebApiDtosLinkDto.linkExpirationId = n.getStringValue(); },
        "linkPasswordId": n => { fromSingaporeWebApiDtosLinkDto.linkPasswordId = n.getStringValue(); },
        "linkVisitLimitId": n => { fromSingaporeWebApiDtosLinkDto.linkVisitLimitId = n.getStringValue(); },
        "originalUri": n => { fromSingaporeWebApiDtosLinkDto.originalUri = n.getStringValue(); },
        "shortCode": n => { fromSingaporeWebApiDtosLinkDto.shortCode = n.getStringValue(); },
        "title": n => { fromSingaporeWebApiDtosLinkDto.title = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFromSingaporeWebApiDtosPlanDto(fromSingaporeWebApiDtosPlanDto: Partial<FromSingaporeWebApiDtosPlanDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "features": n => { fromSingaporeWebApiDtosPlanDto.features = n.getObjectValue<FromSingaporeWebApiDtosPlanDto_PlanFeaturesDto>(createFromSingaporeWebApiDtosPlanDto_PlanFeaturesDtoFromDiscriminatorValue); },
        "id": n => { fromSingaporeWebApiDtosPlanDto.id = n.getStringValue(); },
        "name": n => { fromSingaporeWebApiDtosPlanDto.name = n.getStringValue(); },
        "priceAmount": n => { fromSingaporeWebApiDtosPlanDto.priceAmount = n.getNumberValue(); },
        "priceCurrency": n => { fromSingaporeWebApiDtosPlanDto.priceCurrency = n.getStringValue(); },
        "stripePriceId": n => { fromSingaporeWebApiDtosPlanDto.stripePriceId = n.getStringValue(); },
        "stripeProductId": n => { fromSingaporeWebApiDtosPlanDto.stripeProductId = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFromSingaporeWebApiDtosPlanDto_PlanFeaturesDto(fromSingaporeWebApiDtosPlanDto_PlanFeaturesDto: Partial<FromSingaporeWebApiDtosPlanDto_PlanFeaturesDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "domainsAvailable": n => { fromSingaporeWebApiDtosPlanDto_PlanFeaturesDto.domainsAvailable = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFromSingaporeWebApiDtosSubscriptionDto(fromSingaporeWebApiDtosSubscriptionDto: Partial<FromSingaporeWebApiDtosSubscriptionDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "endDate": n => { fromSingaporeWebApiDtosSubscriptionDto.endDate = n.getDateValue(); },
        "features": n => { fromSingaporeWebApiDtosSubscriptionDto.features = n.getObjectValue<FromSingaporeWebApiDtosSubscriptionDto_PlanFeaturesDto>(createFromSingaporeWebApiDtosSubscriptionDto_PlanFeaturesDtoFromDiscriminatorValue); },
        "id": n => { fromSingaporeWebApiDtosSubscriptionDto.id = n.getStringValue(); },
        "isActive": n => { fromSingaporeWebApiDtosSubscriptionDto.isActive = n.getBooleanValue(); },
        "name": n => { fromSingaporeWebApiDtosSubscriptionDto.name = n.getStringValue(); },
        "priceAmount": n => { fromSingaporeWebApiDtosSubscriptionDto.priceAmount = n.getNumberValue(); },
        "priceCurrency": n => { fromSingaporeWebApiDtosSubscriptionDto.priceCurrency = n.getStringValue(); },
        "startDate": n => { fromSingaporeWebApiDtosSubscriptionDto.startDate = n.getDateValue(); },
        "stripePriceId": n => { fromSingaporeWebApiDtosSubscriptionDto.stripePriceId = n.getStringValue(); },
        "stripeProductId": n => { fromSingaporeWebApiDtosSubscriptionDto.stripeProductId = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFromSingaporeWebApiDtosSubscriptionDto_PlanFeaturesDto(fromSingaporeWebApiDtosSubscriptionDto_PlanFeaturesDto: Partial<FromSingaporeWebApiDtosSubscriptionDto_PlanFeaturesDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "domainsAvailable": n => { fromSingaporeWebApiDtosSubscriptionDto_PlanFeaturesDto.domainsAvailable = n.getNumberValue(); },
        "domainsRemaining": n => { fromSingaporeWebApiDtosSubscriptionDto_PlanFeaturesDto.domainsRemaining = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFromSingaporeWebApiEndpointsDomainListDomainsResponse(fromSingaporeWebApiEndpointsDomainListDomainsResponse: Partial<FromSingaporeWebApiEndpointsDomainListDomainsResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "domains": n => { fromSingaporeWebApiEndpointsDomainListDomainsResponse.domains = n.getCollectionOfObjectValues<FromSingaporeWebApiDtosDomainDto>(createFromSingaporeWebApiDtosDomainDtoFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFromSingaporeWebApiEndpointsDomainQueryDomainsResponse(fromSingaporeWebApiEndpointsDomainQueryDomainsResponse: Partial<FromSingaporeWebApiEndpointsDomainQueryDomainsResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "available": n => { fromSingaporeWebApiEndpointsDomainQueryDomainsResponse.available = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFromSingaporeWebApiEndpointsLinkCreateLinkRequest(fromSingaporeWebApiEndpointsLinkCreateLinkRequest: Partial<FromSingaporeWebApiEndpointsLinkCreateLinkRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "description": n => { fromSingaporeWebApiEndpointsLinkCreateLinkRequest.description = n.getStringValue(); },
        "domainId": n => { fromSingaporeWebApiEndpointsLinkCreateLinkRequest.domainId = n.getStringValue(); },
        "originalUri": n => { fromSingaporeWebApiEndpointsLinkCreateLinkRequest.originalUri = n.getStringValue(); },
        "shortCode": n => { fromSingaporeWebApiEndpointsLinkCreateLinkRequest.shortCode = n.getStringValue(); },
        "title": n => { fromSingaporeWebApiEndpointsLinkCreateLinkRequest.title = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFromSingaporeWebApiEndpointsLinkListLinksResponse(fromSingaporeWebApiEndpointsLinkListLinksResponse: Partial<FromSingaporeWebApiEndpointsLinkListLinksResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "links": n => { fromSingaporeWebApiEndpointsLinkListLinksResponse.links = n.getCollectionOfObjectValues<FromSingaporeWebApiDtosLinkDto>(createFromSingaporeWebApiDtosLinkDtoFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFromSingaporeWebApiEndpointsPlanListPlansResponse(fromSingaporeWebApiEndpointsPlanListPlansResponse: Partial<FromSingaporeWebApiEndpointsPlanListPlansResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "plans": n => { fromSingaporeWebApiEndpointsPlanListPlansResponse.plans = n.getCollectionOfObjectValues<FromSingaporeWebApiDtosPlanDto>(createFromSingaporeWebApiDtosPlanDtoFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFromSingaporeWebApiEndpointsUserGetUserSubscriptionsResponse(fromSingaporeWebApiEndpointsUserGetUserSubscriptionsResponse: Partial<FromSingaporeWebApiEndpointsUserGetUserSubscriptionsResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "subscription": n => { fromSingaporeWebApiEndpointsUserGetUserSubscriptionsResponse.subscription = n.getObjectValue<FromSingaporeWebApiDtosSubscriptionDto>(createFromSingaporeWebApiDtosSubscriptionDtoFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFromSingaporeWebApiExtensionsIdentityInfoResponse(fromSingaporeWebApiExtensionsIdentityInfoResponse: Partial<FromSingaporeWebApiExtensionsIdentityInfoResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { fromSingaporeWebApiExtensionsIdentityInfoResponse.email = n.getStringValue(); },
        "id": n => { fromSingaporeWebApiExtensionsIdentityInfoResponse.id = n.getStringValue(); },
        "isEmailConfirmed": n => { fromSingaporeWebApiExtensionsIdentityInfoResponse.isEmailConfirmed = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMicrosoftAspNetCoreAuthenticationBearerTokenAccessTokenResponse(microsoftAspNetCoreAuthenticationBearerTokenAccessTokenResponse: Partial<MicrosoftAspNetCoreAuthenticationBearerTokenAccessTokenResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "accessToken": n => { microsoftAspNetCoreAuthenticationBearerTokenAccessTokenResponse.accessToken = n.getStringValue(); },
        "expiresIn": n => { microsoftAspNetCoreAuthenticationBearerTokenAccessTokenResponse.expiresIn = n.getNumberValue(); },
        "refreshToken": n => { microsoftAspNetCoreAuthenticationBearerTokenAccessTokenResponse.refreshToken = n.getStringValue(); },
        "tokenType": n => { microsoftAspNetCoreAuthenticationBearerTokenAccessTokenResponse.tokenType = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMicrosoftAspNetCoreHttpHttpValidationProblemDetails(microsoftAspNetCoreHttpHttpValidationProblemDetails: Partial<MicrosoftAspNetCoreHttpHttpValidationProblemDetails> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoMicrosoftAspNetCoreMvcProblemDetails(microsoftAspNetCoreHttpHttpValidationProblemDetails),
        "errors": n => { microsoftAspNetCoreHttpHttpValidationProblemDetails.errors = n.getObjectValue<MicrosoftAspNetCoreHttpHttpValidationProblemDetails_errors>(createMicrosoftAspNetCoreHttpHttpValidationProblemDetails_errorsFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMicrosoftAspNetCoreHttpHttpValidationProblemDetails_errors(microsoftAspNetCoreHttpHttpValidationProblemDetails_errors: Partial<MicrosoftAspNetCoreHttpHttpValidationProblemDetails_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMicrosoftAspNetCoreIdentityDataForgotPasswordRequest(microsoftAspNetCoreIdentityDataForgotPasswordRequest: Partial<MicrosoftAspNetCoreIdentityDataForgotPasswordRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { microsoftAspNetCoreIdentityDataForgotPasswordRequest.email = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMicrosoftAspNetCoreIdentityDataInfoRequest(microsoftAspNetCoreIdentityDataInfoRequest: Partial<MicrosoftAspNetCoreIdentityDataInfoRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "newEmail": n => { microsoftAspNetCoreIdentityDataInfoRequest.newEmail = n.getStringValue(); },
        "newPassword": n => { microsoftAspNetCoreIdentityDataInfoRequest.newPassword = n.getStringValue(); },
        "oldPassword": n => { microsoftAspNetCoreIdentityDataInfoRequest.oldPassword = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMicrosoftAspNetCoreIdentityDataLoginRequest(microsoftAspNetCoreIdentityDataLoginRequest: Partial<MicrosoftAspNetCoreIdentityDataLoginRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { microsoftAspNetCoreIdentityDataLoginRequest.email = n.getStringValue(); },
        "password": n => { microsoftAspNetCoreIdentityDataLoginRequest.password = n.getStringValue(); },
        "twoFactorCode": n => { microsoftAspNetCoreIdentityDataLoginRequest.twoFactorCode = n.getStringValue(); },
        "twoFactorRecoveryCode": n => { microsoftAspNetCoreIdentityDataLoginRequest.twoFactorRecoveryCode = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMicrosoftAspNetCoreIdentityDataRefreshRequest(microsoftAspNetCoreIdentityDataRefreshRequest: Partial<MicrosoftAspNetCoreIdentityDataRefreshRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "refreshToken": n => { microsoftAspNetCoreIdentityDataRefreshRequest.refreshToken = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMicrosoftAspNetCoreIdentityDataRegisterRequest(microsoftAspNetCoreIdentityDataRegisterRequest: Partial<MicrosoftAspNetCoreIdentityDataRegisterRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { microsoftAspNetCoreIdentityDataRegisterRequest.email = n.getStringValue(); },
        "password": n => { microsoftAspNetCoreIdentityDataRegisterRequest.password = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMicrosoftAspNetCoreIdentityDataResendConfirmationEmailRequest(microsoftAspNetCoreIdentityDataResendConfirmationEmailRequest: Partial<MicrosoftAspNetCoreIdentityDataResendConfirmationEmailRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { microsoftAspNetCoreIdentityDataResendConfirmationEmailRequest.email = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMicrosoftAspNetCoreIdentityDataResetPasswordRequest(microsoftAspNetCoreIdentityDataResetPasswordRequest: Partial<MicrosoftAspNetCoreIdentityDataResetPasswordRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { microsoftAspNetCoreIdentityDataResetPasswordRequest.email = n.getStringValue(); },
        "newPassword": n => { microsoftAspNetCoreIdentityDataResetPasswordRequest.newPassword = n.getStringValue(); },
        "resetCode": n => { microsoftAspNetCoreIdentityDataResetPasswordRequest.resetCode = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMicrosoftAspNetCoreIdentityDataTwoFactorRequest(microsoftAspNetCoreIdentityDataTwoFactorRequest: Partial<MicrosoftAspNetCoreIdentityDataTwoFactorRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "enable": n => { microsoftAspNetCoreIdentityDataTwoFactorRequest.enable = n.getBooleanValue(); },
        "forgetMachine": n => { microsoftAspNetCoreIdentityDataTwoFactorRequest.forgetMachine = n.getBooleanValue(); },
        "resetRecoveryCodes": n => { microsoftAspNetCoreIdentityDataTwoFactorRequest.resetRecoveryCodes = n.getBooleanValue(); },
        "resetSharedKey": n => { microsoftAspNetCoreIdentityDataTwoFactorRequest.resetSharedKey = n.getBooleanValue(); },
        "twoFactorCode": n => { microsoftAspNetCoreIdentityDataTwoFactorRequest.twoFactorCode = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMicrosoftAspNetCoreIdentityDataTwoFactorResponse(microsoftAspNetCoreIdentityDataTwoFactorResponse: Partial<MicrosoftAspNetCoreIdentityDataTwoFactorResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "isMachineRemembered": n => { microsoftAspNetCoreIdentityDataTwoFactorResponse.isMachineRemembered = n.getBooleanValue(); },
        "isTwoFactorEnabled": n => { microsoftAspNetCoreIdentityDataTwoFactorResponse.isTwoFactorEnabled = n.getBooleanValue(); },
        "recoveryCodes": n => { microsoftAspNetCoreIdentityDataTwoFactorResponse.recoveryCodes = n.getCollectionOfPrimitiveValues<string>(); },
        "recoveryCodesLeft": n => { microsoftAspNetCoreIdentityDataTwoFactorResponse.recoveryCodesLeft = n.getNumberValue(); },
        "sharedKey": n => { microsoftAspNetCoreIdentityDataTwoFactorResponse.sharedKey = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMicrosoftAspNetCoreMvcProblemDetails(microsoftAspNetCoreMvcProblemDetails: Partial<MicrosoftAspNetCoreMvcProblemDetails> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "detail": n => { microsoftAspNetCoreMvcProblemDetails.detail = n.getStringValue(); },
        "instance": n => { microsoftAspNetCoreMvcProblemDetails.instance = n.getStringValue(); },
        "status": n => { microsoftAspNetCoreMvcProblemDetails.status = n.getNumberValue(); },
        "title": n => { microsoftAspNetCoreMvcProblemDetails.title = n.getStringValue(); },
        "type": n => { microsoftAspNetCoreMvcProblemDetails.type = n.getStringValue(); },
    }
}
export interface FromSingaporeWebApiDtosDomainDto extends Parsable {
    /**
     * The description property
     */
    description?: string;
    /**
     * The id property
     */
    id?: string;
    /**
     * The name property
     */
    name?: string;
}
export interface FromSingaporeWebApiDtosLinkDto extends Parsable {
    /**
     * The description property
     */
    description?: string;
    /**
     * The domainId property
     */
    domainId?: string;
    /**
     * The id property
     */
    id?: string;
    /**
     * The linkExpirationId property
     */
    linkExpirationId?: string;
    /**
     * The linkPasswordId property
     */
    linkPasswordId?: string;
    /**
     * The linkVisitLimitId property
     */
    linkVisitLimitId?: string;
    /**
     * The originalUri property
     */
    originalUri?: string;
    /**
     * The shortCode property
     */
    shortCode?: string;
    /**
     * The title property
     */
    title?: string;
}
export interface FromSingaporeWebApiDtosPlanDto extends Parsable {
    /**
     * The features property
     */
    features?: FromSingaporeWebApiDtosPlanDto_PlanFeaturesDto;
    /**
     * The id property
     */
    id?: string;
    /**
     * The name property
     */
    name?: string;
    /**
     * The priceAmount property
     */
    priceAmount?: number;
    /**
     * The priceCurrency property
     */
    priceCurrency?: string;
    /**
     * The stripePriceId property
     */
    stripePriceId?: string;
    /**
     * The stripeProductId property
     */
    stripeProductId?: string;
}
export interface FromSingaporeWebApiDtosPlanDto_PlanFeaturesDto extends Parsable {
    /**
     * The domainsAvailable property
     */
    domainsAvailable?: number;
}
export interface FromSingaporeWebApiDtosSubscriptionDto extends Parsable {
    /**
     * The endDate property
     */
    endDate?: Date;
    /**
     * The features property
     */
    features?: FromSingaporeWebApiDtosSubscriptionDto_PlanFeaturesDto;
    /**
     * The id property
     */
    id?: string;
    /**
     * The isActive property
     */
    isActive?: boolean;
    /**
     * The name property
     */
    name?: string;
    /**
     * The priceAmount property
     */
    priceAmount?: number;
    /**
     * The priceCurrency property
     */
    priceCurrency?: string;
    /**
     * The startDate property
     */
    startDate?: Date;
    /**
     * The stripePriceId property
     */
    stripePriceId?: string;
    /**
     * The stripeProductId property
     */
    stripeProductId?: string;
}
export interface FromSingaporeWebApiDtosSubscriptionDto_PlanFeaturesDto extends Parsable {
    /**
     * The domainsAvailable property
     */
    domainsAvailable?: number;
    /**
     * The domainsRemaining property
     */
    domainsRemaining?: number;
}
export interface FromSingaporeWebApiEndpointsDomainListDomainsResponse extends Parsable {
    /**
     * The domains property
     */
    domains?: FromSingaporeWebApiDtosDomainDto[];
}
export interface FromSingaporeWebApiEndpointsDomainQueryDomainsResponse extends Parsable {
    /**
     * The available property
     */
    available?: boolean;
}
export interface FromSingaporeWebApiEndpointsLinkCreateLinkRequest extends Parsable {
    /**
     * The description property
     */
    description?: string;
    /**
     * The domainId property
     */
    domainId?: string;
    /**
     * The originalUri property
     */
    originalUri?: string;
    /**
     * The shortCode property
     */
    shortCode?: string;
    /**
     * The title property
     */
    title?: string;
}
export interface FromSingaporeWebApiEndpointsLinkListLinksResponse extends Parsable {
    /**
     * The links property
     */
    links?: FromSingaporeWebApiDtosLinkDto[];
}
export interface FromSingaporeWebApiEndpointsPlanListPlansResponse extends Parsable {
    /**
     * The plans property
     */
    plans?: FromSingaporeWebApiDtosPlanDto[];
}
export interface FromSingaporeWebApiEndpointsUserGetUserSubscriptionsResponse extends Parsable {
    /**
     * The subscription property
     */
    subscription?: FromSingaporeWebApiDtosSubscriptionDto;
}
export interface FromSingaporeWebApiExtensionsIdentityInfoResponse extends Parsable {
    /**
     * The email property
     */
    email?: string;
    /**
     * The id property
     */
    id?: string;
    /**
     * The isEmailConfirmed property
     */
    isEmailConfirmed?: boolean;
}
export interface MicrosoftAspNetCoreAuthenticationBearerTokenAccessTokenResponse extends Parsable {
    /**
     * The accessToken property
     */
    accessToken?: string;
    /**
     * The expiresIn property
     */
    expiresIn?: number;
    /**
     * The refreshToken property
     */
    refreshToken?: string;
    /**
     * The tokenType property
     */
    tokenType?: string;
}
export interface MicrosoftAspNetCoreHttpHttpValidationProblemDetails extends ApiError, MicrosoftAspNetCoreMvcProblemDetails, Parsable {
    /**
     * The errors property
     */
    errors?: MicrosoftAspNetCoreHttpHttpValidationProblemDetails_errors;
}
export interface MicrosoftAspNetCoreHttpHttpValidationProblemDetails_errors extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
}
export interface MicrosoftAspNetCoreIdentityDataForgotPasswordRequest extends Parsable {
    /**
     * The email property
     */
    email?: string;
}
export interface MicrosoftAspNetCoreIdentityDataInfoRequest extends Parsable {
    /**
     * The newEmail property
     */
    newEmail?: string;
    /**
     * The newPassword property
     */
    newPassword?: string;
    /**
     * The oldPassword property
     */
    oldPassword?: string;
}
export interface MicrosoftAspNetCoreIdentityDataLoginRequest extends Parsable {
    /**
     * The email property
     */
    email?: string;
    /**
     * The password property
     */
    password?: string;
    /**
     * The twoFactorCode property
     */
    twoFactorCode?: string;
    /**
     * The twoFactorRecoveryCode property
     */
    twoFactorRecoveryCode?: string;
}
export interface MicrosoftAspNetCoreIdentityDataRefreshRequest extends Parsable {
    /**
     * The refreshToken property
     */
    refreshToken?: string;
}
export interface MicrosoftAspNetCoreIdentityDataRegisterRequest extends Parsable {
    /**
     * The email property
     */
    email?: string;
    /**
     * The password property
     */
    password?: string;
}
export interface MicrosoftAspNetCoreIdentityDataResendConfirmationEmailRequest extends Parsable {
    /**
     * The email property
     */
    email?: string;
}
export interface MicrosoftAspNetCoreIdentityDataResetPasswordRequest extends Parsable {
    /**
     * The email property
     */
    email?: string;
    /**
     * The newPassword property
     */
    newPassword?: string;
    /**
     * The resetCode property
     */
    resetCode?: string;
}
export interface MicrosoftAspNetCoreIdentityDataTwoFactorRequest extends Parsable {
    /**
     * The enable property
     */
    enable?: boolean;
    /**
     * The forgetMachine property
     */
    forgetMachine?: boolean;
    /**
     * The resetRecoveryCodes property
     */
    resetRecoveryCodes?: boolean;
    /**
     * The resetSharedKey property
     */
    resetSharedKey?: boolean;
    /**
     * The twoFactorCode property
     */
    twoFactorCode?: string;
}
export interface MicrosoftAspNetCoreIdentityDataTwoFactorResponse extends Parsable {
    /**
     * The isMachineRemembered property
     */
    isMachineRemembered?: boolean;
    /**
     * The isTwoFactorEnabled property
     */
    isTwoFactorEnabled?: boolean;
    /**
     * The recoveryCodes property
     */
    recoveryCodes?: string[];
    /**
     * The recoveryCodesLeft property
     */
    recoveryCodesLeft?: number;
    /**
     * The sharedKey property
     */
    sharedKey?: string;
}
export interface MicrosoftAspNetCoreMvcProblemDetails extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The detail property
     */
    detail?: string;
    /**
     * The instance property
     */
    instance?: string;
    /**
     * The status property
     */
    status?: number;
    /**
     * The title property
     */
    title?: string;
    /**
     * The type property
     */
    type?: string;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFromSingaporeWebApiDtosDomainDto(writer: SerializationWriter, fromSingaporeWebApiDtosDomainDto: Partial<FromSingaporeWebApiDtosDomainDto> | undefined = {}) : void {
    writer.writeStringValue("description", fromSingaporeWebApiDtosDomainDto.description);
    writer.writeStringValue("id", fromSingaporeWebApiDtosDomainDto.id);
    writer.writeStringValue("name", fromSingaporeWebApiDtosDomainDto.name);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFromSingaporeWebApiDtosLinkDto(writer: SerializationWriter, fromSingaporeWebApiDtosLinkDto: Partial<FromSingaporeWebApiDtosLinkDto> | undefined = {}) : void {
    writer.writeStringValue("description", fromSingaporeWebApiDtosLinkDto.description);
    writer.writeStringValue("domainId", fromSingaporeWebApiDtosLinkDto.domainId);
    writer.writeStringValue("id", fromSingaporeWebApiDtosLinkDto.id);
    writer.writeStringValue("linkExpirationId", fromSingaporeWebApiDtosLinkDto.linkExpirationId);
    writer.writeStringValue("linkPasswordId", fromSingaporeWebApiDtosLinkDto.linkPasswordId);
    writer.writeStringValue("linkVisitLimitId", fromSingaporeWebApiDtosLinkDto.linkVisitLimitId);
    writer.writeStringValue("originalUri", fromSingaporeWebApiDtosLinkDto.originalUri);
    writer.writeStringValue("shortCode", fromSingaporeWebApiDtosLinkDto.shortCode);
    writer.writeStringValue("title", fromSingaporeWebApiDtosLinkDto.title);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFromSingaporeWebApiDtosPlanDto(writer: SerializationWriter, fromSingaporeWebApiDtosPlanDto: Partial<FromSingaporeWebApiDtosPlanDto> | undefined = {}) : void {
    writer.writeObjectValue<FromSingaporeWebApiDtosPlanDto_PlanFeaturesDto>("features", fromSingaporeWebApiDtosPlanDto.features, serializeFromSingaporeWebApiDtosPlanDto_PlanFeaturesDto);
    writer.writeStringValue("id", fromSingaporeWebApiDtosPlanDto.id);
    writer.writeStringValue("name", fromSingaporeWebApiDtosPlanDto.name);
    writer.writeNumberValue("priceAmount", fromSingaporeWebApiDtosPlanDto.priceAmount);
    writer.writeStringValue("priceCurrency", fromSingaporeWebApiDtosPlanDto.priceCurrency);
    writer.writeStringValue("stripePriceId", fromSingaporeWebApiDtosPlanDto.stripePriceId);
    writer.writeStringValue("stripeProductId", fromSingaporeWebApiDtosPlanDto.stripeProductId);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFromSingaporeWebApiDtosPlanDto_PlanFeaturesDto(writer: SerializationWriter, fromSingaporeWebApiDtosPlanDto_PlanFeaturesDto: Partial<FromSingaporeWebApiDtosPlanDto_PlanFeaturesDto> | undefined = {}) : void {
    writer.writeNumberValue("domainsAvailable", fromSingaporeWebApiDtosPlanDto_PlanFeaturesDto.domainsAvailable);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFromSingaporeWebApiDtosSubscriptionDto(writer: SerializationWriter, fromSingaporeWebApiDtosSubscriptionDto: Partial<FromSingaporeWebApiDtosSubscriptionDto> | undefined = {}) : void {
    writer.writeDateValue("endDate", fromSingaporeWebApiDtosSubscriptionDto.endDate);
    writer.writeObjectValue<FromSingaporeWebApiDtosSubscriptionDto_PlanFeaturesDto>("features", fromSingaporeWebApiDtosSubscriptionDto.features, serializeFromSingaporeWebApiDtosSubscriptionDto_PlanFeaturesDto);
    writer.writeStringValue("id", fromSingaporeWebApiDtosSubscriptionDto.id);
    writer.writeBooleanValue("isActive", fromSingaporeWebApiDtosSubscriptionDto.isActive);
    writer.writeStringValue("name", fromSingaporeWebApiDtosSubscriptionDto.name);
    writer.writeNumberValue("priceAmount", fromSingaporeWebApiDtosSubscriptionDto.priceAmount);
    writer.writeStringValue("priceCurrency", fromSingaporeWebApiDtosSubscriptionDto.priceCurrency);
    writer.writeDateValue("startDate", fromSingaporeWebApiDtosSubscriptionDto.startDate);
    writer.writeStringValue("stripePriceId", fromSingaporeWebApiDtosSubscriptionDto.stripePriceId);
    writer.writeStringValue("stripeProductId", fromSingaporeWebApiDtosSubscriptionDto.stripeProductId);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFromSingaporeWebApiDtosSubscriptionDto_PlanFeaturesDto(writer: SerializationWriter, fromSingaporeWebApiDtosSubscriptionDto_PlanFeaturesDto: Partial<FromSingaporeWebApiDtosSubscriptionDto_PlanFeaturesDto> | undefined = {}) : void {
    writer.writeNumberValue("domainsAvailable", fromSingaporeWebApiDtosSubscriptionDto_PlanFeaturesDto.domainsAvailable);
    writer.writeNumberValue("domainsRemaining", fromSingaporeWebApiDtosSubscriptionDto_PlanFeaturesDto.domainsRemaining);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFromSingaporeWebApiEndpointsDomainListDomainsResponse(writer: SerializationWriter, fromSingaporeWebApiEndpointsDomainListDomainsResponse: Partial<FromSingaporeWebApiEndpointsDomainListDomainsResponse> | undefined = {}) : void {
    writer.writeCollectionOfObjectValues<FromSingaporeWebApiDtosDomainDto>("domains", fromSingaporeWebApiEndpointsDomainListDomainsResponse.domains, serializeFromSingaporeWebApiDtosDomainDto);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFromSingaporeWebApiEndpointsDomainQueryDomainsResponse(writer: SerializationWriter, fromSingaporeWebApiEndpointsDomainQueryDomainsResponse: Partial<FromSingaporeWebApiEndpointsDomainQueryDomainsResponse> | undefined = {}) : void {
    writer.writeBooleanValue("available", fromSingaporeWebApiEndpointsDomainQueryDomainsResponse.available);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFromSingaporeWebApiEndpointsLinkCreateLinkRequest(writer: SerializationWriter, fromSingaporeWebApiEndpointsLinkCreateLinkRequest: Partial<FromSingaporeWebApiEndpointsLinkCreateLinkRequest> | undefined = {}) : void {
    writer.writeStringValue("description", fromSingaporeWebApiEndpointsLinkCreateLinkRequest.description);
    writer.writeStringValue("domainId", fromSingaporeWebApiEndpointsLinkCreateLinkRequest.domainId);
    writer.writeStringValue("originalUri", fromSingaporeWebApiEndpointsLinkCreateLinkRequest.originalUri);
    writer.writeStringValue("shortCode", fromSingaporeWebApiEndpointsLinkCreateLinkRequest.shortCode);
    writer.writeStringValue("title", fromSingaporeWebApiEndpointsLinkCreateLinkRequest.title);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFromSingaporeWebApiEndpointsLinkListLinksResponse(writer: SerializationWriter, fromSingaporeWebApiEndpointsLinkListLinksResponse: Partial<FromSingaporeWebApiEndpointsLinkListLinksResponse> | undefined = {}) : void {
    writer.writeCollectionOfObjectValues<FromSingaporeWebApiDtosLinkDto>("links", fromSingaporeWebApiEndpointsLinkListLinksResponse.links, serializeFromSingaporeWebApiDtosLinkDto);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFromSingaporeWebApiEndpointsPlanListPlansResponse(writer: SerializationWriter, fromSingaporeWebApiEndpointsPlanListPlansResponse: Partial<FromSingaporeWebApiEndpointsPlanListPlansResponse> | undefined = {}) : void {
    writer.writeCollectionOfObjectValues<FromSingaporeWebApiDtosPlanDto>("plans", fromSingaporeWebApiEndpointsPlanListPlansResponse.plans, serializeFromSingaporeWebApiDtosPlanDto);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFromSingaporeWebApiEndpointsUserGetUserSubscriptionsResponse(writer: SerializationWriter, fromSingaporeWebApiEndpointsUserGetUserSubscriptionsResponse: Partial<FromSingaporeWebApiEndpointsUserGetUserSubscriptionsResponse> | undefined = {}) : void {
    writer.writeObjectValue<FromSingaporeWebApiDtosSubscriptionDto>("subscription", fromSingaporeWebApiEndpointsUserGetUserSubscriptionsResponse.subscription, serializeFromSingaporeWebApiDtosSubscriptionDto);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFromSingaporeWebApiExtensionsIdentityInfoResponse(writer: SerializationWriter, fromSingaporeWebApiExtensionsIdentityInfoResponse: Partial<FromSingaporeWebApiExtensionsIdentityInfoResponse> | undefined = {}) : void {
    writer.writeStringValue("email", fromSingaporeWebApiExtensionsIdentityInfoResponse.email);
    writer.writeStringValue("id", fromSingaporeWebApiExtensionsIdentityInfoResponse.id);
    writer.writeBooleanValue("isEmailConfirmed", fromSingaporeWebApiExtensionsIdentityInfoResponse.isEmailConfirmed);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMicrosoftAspNetCoreAuthenticationBearerTokenAccessTokenResponse(writer: SerializationWriter, microsoftAspNetCoreAuthenticationBearerTokenAccessTokenResponse: Partial<MicrosoftAspNetCoreAuthenticationBearerTokenAccessTokenResponse> | undefined = {}) : void {
    writer.writeStringValue("accessToken", microsoftAspNetCoreAuthenticationBearerTokenAccessTokenResponse.accessToken);
    writer.writeNumberValue("expiresIn", microsoftAspNetCoreAuthenticationBearerTokenAccessTokenResponse.expiresIn);
    writer.writeStringValue("refreshToken", microsoftAspNetCoreAuthenticationBearerTokenAccessTokenResponse.refreshToken);
    writer.writeStringValue("tokenType", microsoftAspNetCoreAuthenticationBearerTokenAccessTokenResponse.tokenType);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMicrosoftAspNetCoreHttpHttpValidationProblemDetails(writer: SerializationWriter, microsoftAspNetCoreHttpHttpValidationProblemDetails: Partial<MicrosoftAspNetCoreHttpHttpValidationProblemDetails> | undefined = {}) : void {
    serializeMicrosoftAspNetCoreMvcProblemDetails(writer, microsoftAspNetCoreHttpHttpValidationProblemDetails)
    writer.writeObjectValue<MicrosoftAspNetCoreHttpHttpValidationProblemDetails_errors>("errors", microsoftAspNetCoreHttpHttpValidationProblemDetails.errors, serializeMicrosoftAspNetCoreHttpHttpValidationProblemDetails_errors);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMicrosoftAspNetCoreHttpHttpValidationProblemDetails_errors(writer: SerializationWriter, microsoftAspNetCoreHttpHttpValidationProblemDetails_errors: Partial<MicrosoftAspNetCoreHttpHttpValidationProblemDetails_errors> | undefined = {}) : void {
    writer.writeAdditionalData(microsoftAspNetCoreHttpHttpValidationProblemDetails_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMicrosoftAspNetCoreIdentityDataForgotPasswordRequest(writer: SerializationWriter, microsoftAspNetCoreIdentityDataForgotPasswordRequest: Partial<MicrosoftAspNetCoreIdentityDataForgotPasswordRequest> | undefined = {}) : void {
    writer.writeStringValue("email", microsoftAspNetCoreIdentityDataForgotPasswordRequest.email);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMicrosoftAspNetCoreIdentityDataInfoRequest(writer: SerializationWriter, microsoftAspNetCoreIdentityDataInfoRequest: Partial<MicrosoftAspNetCoreIdentityDataInfoRequest> | undefined = {}) : void {
    writer.writeStringValue("newEmail", microsoftAspNetCoreIdentityDataInfoRequest.newEmail);
    writer.writeStringValue("newPassword", microsoftAspNetCoreIdentityDataInfoRequest.newPassword);
    writer.writeStringValue("oldPassword", microsoftAspNetCoreIdentityDataInfoRequest.oldPassword);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMicrosoftAspNetCoreIdentityDataLoginRequest(writer: SerializationWriter, microsoftAspNetCoreIdentityDataLoginRequest: Partial<MicrosoftAspNetCoreIdentityDataLoginRequest> | undefined = {}) : void {
    writer.writeStringValue("email", microsoftAspNetCoreIdentityDataLoginRequest.email);
    writer.writeStringValue("password", microsoftAspNetCoreIdentityDataLoginRequest.password);
    writer.writeStringValue("twoFactorCode", microsoftAspNetCoreIdentityDataLoginRequest.twoFactorCode);
    writer.writeStringValue("twoFactorRecoveryCode", microsoftAspNetCoreIdentityDataLoginRequest.twoFactorRecoveryCode);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMicrosoftAspNetCoreIdentityDataRefreshRequest(writer: SerializationWriter, microsoftAspNetCoreIdentityDataRefreshRequest: Partial<MicrosoftAspNetCoreIdentityDataRefreshRequest> | undefined = {}) : void {
    writer.writeStringValue("refreshToken", microsoftAspNetCoreIdentityDataRefreshRequest.refreshToken);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMicrosoftAspNetCoreIdentityDataRegisterRequest(writer: SerializationWriter, microsoftAspNetCoreIdentityDataRegisterRequest: Partial<MicrosoftAspNetCoreIdentityDataRegisterRequest> | undefined = {}) : void {
    writer.writeStringValue("email", microsoftAspNetCoreIdentityDataRegisterRequest.email);
    writer.writeStringValue("password", microsoftAspNetCoreIdentityDataRegisterRequest.password);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMicrosoftAspNetCoreIdentityDataResendConfirmationEmailRequest(writer: SerializationWriter, microsoftAspNetCoreIdentityDataResendConfirmationEmailRequest: Partial<MicrosoftAspNetCoreIdentityDataResendConfirmationEmailRequest> | undefined = {}) : void {
    writer.writeStringValue("email", microsoftAspNetCoreIdentityDataResendConfirmationEmailRequest.email);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMicrosoftAspNetCoreIdentityDataResetPasswordRequest(writer: SerializationWriter, microsoftAspNetCoreIdentityDataResetPasswordRequest: Partial<MicrosoftAspNetCoreIdentityDataResetPasswordRequest> | undefined = {}) : void {
    writer.writeStringValue("email", microsoftAspNetCoreIdentityDataResetPasswordRequest.email);
    writer.writeStringValue("newPassword", microsoftAspNetCoreIdentityDataResetPasswordRequest.newPassword);
    writer.writeStringValue("resetCode", microsoftAspNetCoreIdentityDataResetPasswordRequest.resetCode);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMicrosoftAspNetCoreIdentityDataTwoFactorRequest(writer: SerializationWriter, microsoftAspNetCoreIdentityDataTwoFactorRequest: Partial<MicrosoftAspNetCoreIdentityDataTwoFactorRequest> | undefined = {}) : void {
    writer.writeBooleanValue("enable", microsoftAspNetCoreIdentityDataTwoFactorRequest.enable);
    writer.writeBooleanValue("forgetMachine", microsoftAspNetCoreIdentityDataTwoFactorRequest.forgetMachine);
    writer.writeBooleanValue("resetRecoveryCodes", microsoftAspNetCoreIdentityDataTwoFactorRequest.resetRecoveryCodes);
    writer.writeBooleanValue("resetSharedKey", microsoftAspNetCoreIdentityDataTwoFactorRequest.resetSharedKey);
    writer.writeStringValue("twoFactorCode", microsoftAspNetCoreIdentityDataTwoFactorRequest.twoFactorCode);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMicrosoftAspNetCoreIdentityDataTwoFactorResponse(writer: SerializationWriter, microsoftAspNetCoreIdentityDataTwoFactorResponse: Partial<MicrosoftAspNetCoreIdentityDataTwoFactorResponse> | undefined = {}) : void {
    writer.writeBooleanValue("isMachineRemembered", microsoftAspNetCoreIdentityDataTwoFactorResponse.isMachineRemembered);
    writer.writeBooleanValue("isTwoFactorEnabled", microsoftAspNetCoreIdentityDataTwoFactorResponse.isTwoFactorEnabled);
    writer.writeCollectionOfPrimitiveValues<string>("recoveryCodes", microsoftAspNetCoreIdentityDataTwoFactorResponse.recoveryCodes);
    writer.writeNumberValue("recoveryCodesLeft", microsoftAspNetCoreIdentityDataTwoFactorResponse.recoveryCodesLeft);
    writer.writeStringValue("sharedKey", microsoftAspNetCoreIdentityDataTwoFactorResponse.sharedKey);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMicrosoftAspNetCoreMvcProblemDetails(writer: SerializationWriter, microsoftAspNetCoreMvcProblemDetails: Partial<MicrosoftAspNetCoreMvcProblemDetails> | undefined = {}) : void {
    writer.writeStringValue("detail", microsoftAspNetCoreMvcProblemDetails.detail);
    writer.writeStringValue("instance", microsoftAspNetCoreMvcProblemDetails.instance);
    writer.writeNumberValue("status", microsoftAspNetCoreMvcProblemDetails.status);
    writer.writeStringValue("title", microsoftAspNetCoreMvcProblemDetails.title);
    writer.writeStringValue("type", microsoftAspNetCoreMvcProblemDetails.type);
    writer.writeAdditionalData(microsoftAspNetCoreMvcProblemDetails.additionalData);
}
/* tslint:enable */
/* eslint-enable */
