/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { serializeMicrosoftAspNetCoreIdentityDataResendConfirmationEmailRequest, type MicrosoftAspNetCoreIdentityDataResendConfirmationEmailRequest } from '../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /resendConfirmationEmail
 */
export interface ResendConfirmationEmailRequestBuilder extends BaseRequestBuilder<ResendConfirmationEmailRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     */
     post(body: MicrosoftAspNetCoreIdentityDataResendConfirmationEmailRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: MicrosoftAspNetCoreIdentityDataResendConfirmationEmailRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ResendConfirmationEmailRequestBuilderUriTemplate = "{+baseurl}/resendConfirmationEmail";
/**
 * Metadata for all the requests in the request builder.
 */
export const ResendConfirmationEmailRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ResendConfirmationEmailRequestBuilderUriTemplate,
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeMicrosoftAspNetCoreIdentityDataResendConfirmationEmailRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
