/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata, UntypedNode } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Stripe/Webhook
 */
export interface WebhookRequestBuilder extends BaseRequestBuilder<WebhookRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UntypedNode>}
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<UntypedNode | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WebhookRequestBuilderUriTemplate = "{+baseurl}/Stripe/Webhook";
/**
 * Metadata for all the requests in the request builder.
 */
export const WebhookRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: WebhookRequestBuilderUriTemplate,
        responseBodyContentType: "text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createUntypedNodeFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
