/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMicrosoftAspNetCoreAuthenticationBearerTokenAccessTokenResponseFromDiscriminatorValue, serializeMicrosoftAspNetCoreAuthenticationBearerTokenAccessTokenResponse, serializeMicrosoftAspNetCoreIdentityDataRefreshRequest, type MicrosoftAspNetCoreAuthenticationBearerTokenAccessTokenResponse, type MicrosoftAspNetCoreIdentityDataRefreshRequest } from '../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /refresh
 */
export interface RefreshRequestBuilder extends BaseRequestBuilder<RefreshRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MicrosoftAspNetCoreAuthenticationBearerTokenAccessTokenResponse>}
     */
     post(body: MicrosoftAspNetCoreIdentityDataRefreshRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MicrosoftAspNetCoreAuthenticationBearerTokenAccessTokenResponse | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: MicrosoftAspNetCoreIdentityDataRefreshRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const RefreshRequestBuilderUriTemplate = "{+baseurl}/refresh";
/**
 * Metadata for all the requests in the request builder.
 */
export const RefreshRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: RefreshRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createMicrosoftAspNetCoreAuthenticationBearerTokenAccessTokenResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeMicrosoftAspNetCoreIdentityDataRefreshRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
