/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { SubscriptionRequestBuilderRequestsMetadata, type SubscriptionRequestBuilder } from './subscription/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /User/{UserId}
 */
export interface WithUserItemRequestBuilder extends BaseRequestBuilder<WithUserItemRequestBuilder> {
    /**
     * The Subscription property
     */
    get subscription(): SubscriptionRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithUserItemRequestBuilderUriTemplate = "{+baseurl}/User/{UserId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithUserItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithUserItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    subscription: {
        requestsMetadata: SubscriptionRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
