// <auto-generated />
using System;
using FromSingapore.Core.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FromSingapore.Migrations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240925134423_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FromSingapore.Core.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("FromSingapore.Core.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FromSingapore.Core.Entities.Domain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Domains");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("FromSingapore.Core.Entities.Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("LinkExpirationId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("LinkPasswordId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("LinkVisitLimitId")
                        .HasColumnType("char(36)");

                    b.Property<string>("OriginalUri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("LinkExpirationId");

                    b.HasIndex("LinkPasswordId");

                    b.HasIndex("LinkVisitLimitId");

                    b.HasIndex("DomainId", "ShortCode")
                        .IsUnique();

                    b.ToTable("Links");
                });

            modelBuilder.Entity("FromSingapore.Core.Entities.LinkExpiration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("LinkExpirations");
                });

            modelBuilder.Entity("FromSingapore.Core.Entities.LinkPassword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("LinkPasswords");
                });

            modelBuilder.Entity("FromSingapore.Core.Entities.LinkVisit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("LinkId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("VisitedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("LinkId");

                    b.ToTable("LinkVisits");
                });

            modelBuilder.Entity("FromSingapore.Core.Entities.LinkVisitLimit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Max")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LinkVisitLimits");
                });

            modelBuilder.Entity("FromSingapore.Core.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Subscriptions");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("FromSingapore.Core.Entities.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FromSingapore.Core.Entities.FreeDomain", b =>
                {
                    b.HasBaseType("FromSingapore.Core.Entities.Domain");

                    b.ToTable("FreeDomains");

                    b.HasData(
                        new
                        {
                            Id = new Guid("04569f15-7a77-4cf3-8477-6b37a1c1fe01"),
                            Description = "Free domain",
                            Name = "from.sg"
                        });
                });

            modelBuilder.Entity("FromSingapore.Core.Entities.PaidDomain", b =>
                {
                    b.HasBaseType("FromSingapore.Core.Entities.Domain");

                    b.Property<Guid>("DomainSubscriptionId")
                        .HasColumnType("char(36)");

                    b.HasIndex("DomainSubscriptionId");

                    b.ToTable("PaidDomains");
                });

            modelBuilder.Entity("FromSingapore.Core.Entities.DomainSubscription", b =>
                {
                    b.HasBaseType("FromSingapore.Core.Entities.Subscription");

                    b.Property<Guid>("DomainSubscriptionPlanId")
                        .HasColumnType("char(36)");

                    b.HasIndex("DomainSubscriptionPlanId");

                    b.ToTable("DomainSubscriptions");
                });

            modelBuilder.Entity("FromSingapore.Core.Entities.LinkSubscription", b =>
                {
                    b.HasBaseType("FromSingapore.Core.Entities.Subscription");

                    b.Property<Guid>("LinkSubscriptionPlanId")
                        .HasColumnType("char(36)");

                    b.HasIndex("LinkSubscriptionPlanId");

                    b.ToTable("LinkSubscriptions");
                });

            modelBuilder.Entity("FromSingapore.Core.Entities.DomainSubscriptionPlan", b =>
                {
                    b.HasBaseType("FromSingapore.Core.Entities.SubscriptionPlan");

                    b.ToTable("DomainSubscriptionPlans");
                });

            modelBuilder.Entity("FromSingapore.Core.Entities.LinkSubscriptionPlan", b =>
                {
                    b.HasBaseType("FromSingapore.Core.Entities.SubscriptionPlan");

                    b.ToTable("LinkSubscriptionPlans");
                });

            modelBuilder.Entity("FromSingapore.Core.Entities.Link", b =>
                {
                    b.HasOne("FromSingapore.Core.Entities.AppUser", "AppUser")
                        .WithMany("Links")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FromSingapore.Core.Entities.Domain", "Domain")
                        .WithMany("Links")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FromSingapore.Core.Entities.LinkExpiration", "LinkExpiration")
                        .WithMany()
                        .HasForeignKey("LinkExpirationId");

                    b.HasOne("FromSingapore.Core.Entities.LinkPassword", "LinkPassword")
                        .WithMany()
                        .HasForeignKey("LinkPasswordId");

                    b.HasOne("FromSingapore.Core.Entities.LinkVisitLimit", "LinkVisitLimit")
                        .WithMany()
                        .HasForeignKey("LinkVisitLimitId");

                    b.Navigation("AppUser");

                    b.Navigation("Domain");

                    b.Navigation("LinkExpiration");

                    b.Navigation("LinkPassword");

                    b.Navigation("LinkVisitLimit");
                });

            modelBuilder.Entity("FromSingapore.Core.Entities.LinkVisit", b =>
                {
                    b.HasOne("FromSingapore.Core.Entities.Link", "Link")
                        .WithMany("LinkVisits")
                        .HasForeignKey("LinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Link");
                });

            modelBuilder.Entity("FromSingapore.Core.Entities.Subscription", b =>
                {
                    b.HasOne("FromSingapore.Core.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("FromSingapore.Core.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("FromSingapore.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("FromSingapore.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("FromSingapore.Core.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FromSingapore.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("FromSingapore.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FromSingapore.Core.Entities.FreeDomain", b =>
                {
                    b.HasOne("FromSingapore.Core.Entities.Domain", null)
                        .WithOne()
                        .HasForeignKey("FromSingapore.Core.Entities.FreeDomain", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FromSingapore.Core.Entities.PaidDomain", b =>
                {
                    b.HasOne("FromSingapore.Core.Entities.DomainSubscription", "DomainSubscription")
                        .WithMany()
                        .HasForeignKey("DomainSubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FromSingapore.Core.Entities.Domain", null)
                        .WithOne()
                        .HasForeignKey("FromSingapore.Core.Entities.PaidDomain", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DomainSubscription");
                });

            modelBuilder.Entity("FromSingapore.Core.Entities.DomainSubscription", b =>
                {
                    b.HasOne("FromSingapore.Core.Entities.DomainSubscriptionPlan", "DomainSubscriptionPlan")
                        .WithMany("DomainSubscriptions")
                        .HasForeignKey("DomainSubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FromSingapore.Core.Entities.Subscription", null)
                        .WithOne()
                        .HasForeignKey("FromSingapore.Core.Entities.DomainSubscription", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DomainSubscriptionPlan");
                });

            modelBuilder.Entity("FromSingapore.Core.Entities.LinkSubscription", b =>
                {
                    b.HasOne("FromSingapore.Core.Entities.Subscription", null)
                        .WithOne()
                        .HasForeignKey("FromSingapore.Core.Entities.LinkSubscription", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FromSingapore.Core.Entities.LinkSubscriptionPlan", "LinkSubscriptionPlan")
                        .WithMany("LinkSubscriptions")
                        .HasForeignKey("LinkSubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinkSubscriptionPlan");
                });

            modelBuilder.Entity("FromSingapore.Core.Entities.DomainSubscriptionPlan", b =>
                {
                    b.HasOne("FromSingapore.Core.Entities.SubscriptionPlan", null)
                        .WithOne()
                        .HasForeignKey("FromSingapore.Core.Entities.DomainSubscriptionPlan", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FromSingapore.Core.Entities.LinkSubscriptionPlan", b =>
                {
                    b.HasOne("FromSingapore.Core.Entities.SubscriptionPlan", null)
                        .WithOne()
                        .HasForeignKey("FromSingapore.Core.Entities.LinkSubscriptionPlan", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FromSingapore.Core.Entities.AppUser", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("FromSingapore.Core.Entities.Domain", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("FromSingapore.Core.Entities.Link", b =>
                {
                    b.Navigation("LinkVisits");
                });

            modelBuilder.Entity("FromSingapore.Core.Entities.DomainSubscriptionPlan", b =>
                {
                    b.Navigation("DomainSubscriptions");
                });

            modelBuilder.Entity("FromSingapore.Core.Entities.LinkSubscriptionPlan", b =>
                {
                    b.Navigation("LinkSubscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
