/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMicrosoftAspNetCoreHttpHttpValidationProblemDetailsFromDiscriminatorValue, createMicrosoftAspNetCoreIdentityDataTwoFactorResponseFromDiscriminatorValue, serializeMicrosoftAspNetCoreIdentityDataTwoFactorRequest, serializeMicrosoftAspNetCoreIdentityDataTwoFactorResponse, type MicrosoftAspNetCoreHttpHttpValidationProblemDetails, type MicrosoftAspNetCoreIdentityDataTwoFactorRequest, type MicrosoftAspNetCoreIdentityDataTwoFactorResponse } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /manage/2fa
 */
export interface TwofaRequestBuilder extends BaseRequestBuilder<TwofaRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MicrosoftAspNetCoreIdentityDataTwoFactorResponse>}
     * @throws {MicrosoftAspNetCoreHttpHttpValidationProblemDetails} error when the service returns a 400 status code
     */
     post(body: MicrosoftAspNetCoreIdentityDataTwoFactorRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MicrosoftAspNetCoreIdentityDataTwoFactorResponse | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: MicrosoftAspNetCoreIdentityDataTwoFactorRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const TwofaRequestBuilderUriTemplate = "{+baseurl}/manage/2fa";
/**
 * Metadata for all the requests in the request builder.
 */
export const TwofaRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: TwofaRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMicrosoftAspNetCoreHttpHttpValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createMicrosoftAspNetCoreIdentityDataTwoFactorResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeMicrosoftAspNetCoreIdentityDataTwoFactorRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
