/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFromSingaporeWebApiEndpointsLinkListLinksResponseFromDiscriminatorValue, type FromSingaporeWebApiEndpointsLinkListLinksResponse } from '../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Link
 */
export interface LinkRequestBuilder extends BaseRequestBuilder<LinkRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FromSingaporeWebApiEndpointsLinkListLinksResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<FromSingaporeWebApiEndpointsLinkListLinksResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const LinkRequestBuilderUriTemplate = "{+baseurl}/Link";
/**
 * Metadata for all the requests in the request builder.
 */
export const LinkRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: LinkRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createFromSingaporeWebApiEndpointsLinkListLinksResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
