/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFromSingaporeWebApiEndpointsPlanListPlansResponseFromDiscriminatorValue, type FromSingaporeWebApiEndpointsPlanListPlansResponse } from '../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Plan
 */
export interface PlanRequestBuilder extends BaseRequestBuilder<PlanRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FromSingaporeWebApiEndpointsPlanListPlansResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<FromSingaporeWebApiEndpointsPlanListPlansResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const PlanRequestBuilderUriTemplate = "{+baseurl}/Plan";
/**
 * Metadata for all the requests in the request builder.
 */
export const PlanRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: PlanRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createFromSingaporeWebApiEndpointsPlanListPlansResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
